baseURL = 'https://www.bram85.nl'
languageCode = 'en-us'
title = 'bram85'
theme = "hugo-theme-monochrome"

[[menu.navbar]]
identifier = "categories"
name = "Categories"
url = "/categories/"
weight = 80

[[menu.navbar]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 80

[params]
footer = "© 2022 - Bram Schoenmakers"
